/*
 * 声纹云api
 *
 * api document
 *
 * API version: /cloudapi/v1beta
 * Contact: xiachengjia@speakin.mobi
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VoiceprintNormalizeRequest struct {
	// 应用名字
	AppName string `json:"appName"`
	// 分数
	Score []float64 `json:"score"`
}
