/*
 * 声纹云api
 *
 * api document
 *
 * API version: /cloudapi/v1beta
 * Contact: xiachengjia@speakin.mobi
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UnionIdScore struct {
	// union ID
	UnionID string `json:"unionID,omitempty"`
	// 得分
	Score float64 `json:"score,omitempty"`
}
