/*
 * voiceprintstorage
 *
 * api document
 *
 * API version: /cloudapi/v1beta
 * Contact: xiachengjia@speakin.mobi
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VoiceprintRegisterRequest struct {
	AppName string `json:"appName"`
	Replace bool `json:"replace,omitempty"`
	UnionID string `json:"unionID"`
	Urls []string `json:"urls,omitempty"`
	SamplingRate string `json:"samplingRate"`
	Timestamp int64 `json:"timestamp"`
}
