/*
 * 声纹云api
 *
 * api document
 *
 * API version: /cloudapi/v1beta
 * Contact: xiachengjia@speakin.mobi
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VoiceprintTtsResponse struct {
	IsTTS bool `json:"isTTS,omitempty"`
	Score float64 `json:"score,omitempty"`
}
