/*
 * 声纹云api
 *
 * api document
 *
 * API version: /cloudapi/v1beta
 * Contact: xiachengjia@speakin.mobi
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VoiceprintVerifyRequest struct {
	// 应用名字
	AppName string `json:"appName"`
	// 唯一ID
	UnionID string `json:"unionID"`
	// 文件url
	Url string `json:"url"`
	// sampling rate
	SamplingRate string `json:"samplingRate"`
	// 时间戳
	Timestamp int64 `json:"timestamp"`
}
