/*
 * 声纹云api
 *
 * api document
 *
 * API version: /cloudapi/v1beta
 * Contact: xiachengjia@speakin.mobi
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Voiceprint1tonVerifyRequest struct {
	// 应用名字
	AppName string `json:"appName"`
	// union IDs
	UnionIDs []string `json:"unionIDs"`
	// 文件url
	Url string `json:"url"`
	// sampling rate
	SamplingRate string `json:"samplingRate"`
	// 时间戳
	Timestamp int64 `json:"timestamp"`
}
