/*
 * 声纹云api
 *
 * api document
 *
 * API version: /cloudapi/v1beta
 * Contact: xiachengjia@speakin.mobi
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VoiceprintDeleteRequest struct {
	// 应用名字
	AppName string `json:"appName"`
	// union ID
	UnionID string `json:"unionID"`
	// 时间戳（以秒为单位）
	Timestamp int64 `json:"timestamp"`
}
