/*
 * 声纹云api
 *
 * api document
 *
 * API version: /cloudapi/v1beta
 * Contact: xiachengjia@speakin.mobi
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VoiceprintVadcheckResponse struct {
	// vad check code
	Code string `json:"code,omitempty"`
	// vad check status
	Status string `json:"status,omitempty"`
}
