/*
 * 声纹云api
 *
 * api document
 *
 * API version: /cloudapi/v1beta
 * Contact: xiachengjia@speakin.mobi
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VoiceprinttopnVerifyRequest struct {
	// 应用名字
	AppName string `json:"appName"`
	// 文件url
	Urls []string `json:"urls"`
	// sampling rate
	SamplingRate string `json:"samplingRate"`
	// top n
	Topn int64 `json:"topn"`
	// 时间戳
	Timestamp int64 `json:"timestamp"`
}
