/*
 * 声纹云api
 *
 * api document
 *
 * API version: /cloudapi/v1beta
 * Contact: xiachengjia@speakin.mobi
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VoiceprintRegisterRequest struct {
	// 应用名字
	AppName string `json:"appName"`
	// 是否替换
	Replace bool `json:"replace,omitempty"`
	// union ID
	UnionID string `json:"unionID"`
	// 文件url数组
	Urls []string `json:"urls,omitempty"`
	// sampling rate
	SamplingRate string `json:"samplingRate"`
	// 时间戳
	Timestamp int64 `json:"timestamp"`
}
