/*
 * voiceprintstorage
 *
 * api document
 *
 * API version: /cloudapi/v1beta
 * Contact: xiachengjia@speakin.mobi
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VoiceprinttopnVerifyResponse struct {
	Scores []UnionIdScore `json:"scores,omitempty"`
}
