/*
 * voiceprintstorage
 *
 * api document
 *
 * API version: /cloudapi/v1beta
 * Contact: xiachengjia@speakin.mobi
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Voiceprint1tonVerifyResponse struct {
	UnionID string `json:"unionID,omitempty"`
	Score float64 `json:"score,omitempty"`
}
