/*
 * 声纹云api
 *
 * api document
 *
 * API version: /cloudapi/v1beta
 * Contact: xiachengjia@speakin.mobi
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VoiceprintVerifyMultiResponse struct {
	// 结果
	Report []VoiceprintVerifyMultiReport `json:"report,omitempty"`
}
