/*
 * 声纹云api
 *
 * api document
 *
 * API version: /cloudapi/v1beta
 * Contact: xiachengjia@speakin.mobi
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VoiceprintDenoiseRequest struct {
	// 应用名字
	AppName string `json:"appName"`
	// 文件url
	Url string `json:"url"`
	// 降噪方法:rnn/winner
	Method string `json:"method"`
	// 降噪力度:0/1/2/3
	Mode int32 `json:"mode,omitempty"`
	// 采样率,8k/16k
	SamplingRate string `json:"samplingRate"`
	// 时长(以秒为单位)
	Duration float64 `json:"duration"`
	// 时间戳（以秒为单位）
	Timestamp int64 `json:"timestamp"`
}
